version: "3"

services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: terms_and_conditions
    ports:
      - "5432:5432"
