spring:
  jackson:
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:5432/${POSTGRESQL_DB:terms_and_conditions}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: ${KEYCLOAK_OIDC_ISSUER:https://auth.staging.fellesdatakatalog.digdir.no/realms/fdk}/protocol/openid-connect/certs
    issuer-uri: ${KEYCLOAK_OIDC_ISSUER:https://auth.staging.fellesdatakatalog.digdir.no/realms/fdk}
logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
application:
  secrets.userApiKey: ${USER_API_KEY}
  cors.originPatterns: "${CORS_ORIGIN_PATTERNS}"
server.port: 8080

---
spring:
  config.activate.on-profile: develop
  datasource:
    url: jdbc:postgresql://localhost:5432/terms_and_conditions
    username: testuser
    password: testpassword
application:
  secrets.userApiKey: userapisecret
  cors.originPatterns: "*"

---
spring:
  config.activate.on-profile: contract-test
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: http://localhost:6000/realms/fdk/protocol/openid-connect/certs
    issuer-uri: http://localhost:6000/realms/fdk
  datasource:
    url: jdbc:postgresql://localhost:5432/terms_and_conditions
    username: testuser
    password: testpassword
application:
  secrets.userApiKey: userapisecret
  cors.originPatterns: "*"
server.port: 5050
