---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - terms-and-conditions-deployment.yaml
  - terms-and-conditions-service.yaml
images:
  - name: terms-and-conditions
    newName: ghcr.io/informasjonsforvaltning/terms-and-conditions
    newTag: $(GIT_COMMIT_SHA)
