apiVersion: v1
kind: Service
metadata:
  labels:
    fdk.service: terms-and-conditions
  name: terms-and-conditions
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    fdk.service: terms-and-conditions
