---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fdk.service: terms-and-conditions
  name: terms-and-conditions
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: terms-and-conditions
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        fdk.service: terms-and-conditions
    spec:
      containers:
        - name: terms-and-conditions
          image: terms-and-conditions
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "500Mi"
              cpu: "50m"
            limits:
              memory: "500Mi"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
      restartPolicy: Always
